DISTRO = "joudar"
DISTRO_NAME = "joudar reference distribution"
DISTRO_VERSION = "1.0"
DISTRO_CODENAME = "scarthgap"

INIT_MANAGER = "systemd"
NO_RECOMMENDATIONS = "1"

DISTRO_FEATURES:append = " rauc"

# use one tmp directory
TCLIBCAPPEND = ""


PREMIRRORS ??= "\
bzr://.*/.*   http://downloads.yoctoproject.org/mirror/sources/ \n \
cvs://.*/.*   http://downloads.yoctoproject.org/mirror/sources/ \n \
git://.*/.*   http://downloads.yoctoproject.org/mirror/sources/ \n \
gitsm://.*/.* http://downloads.yoctoproject.org/mirror/sources/ \n \
hg://.*/.*    http://downloads.yoctoproject.org/mirror/sources/ \n \
osc://.*/.*   http://downloads.yoctoproject.org/mirror/sources/ \n \
p4://.*/.*    http://downloads.yoctoproject.org/mirror/sources/ \n \
svn://.*/.*   http://downloads.yoctoproject.org/mirror/sources/ \n"

MIRRORS =+ "\
ftp://.*/.*      http://downloads.yoctoproject.org/mirror/sources/ \n \
http://.*/.*     http://downloads.yoctoproject.org/mirror/sources/ \n \
https://.*/.*    http://downloads.yoctoproject.org/mirror/sources/ \n"

#remove gpl v3
require conf/distro/include/no-gplv3.inc

#security flags
require conf/distro/include/security_flags.inc

#Distro features
DISTRO_FEATURES = "\
    acl\ 
    bluetooth \
    ext2 \
    ipv4 \
    ipv6 \
    usbgadget \
    usbhost \
    wifi \
    xattr \
    zeroconf \
    pci \
    vfat \
    seccomp \
    systemd \
"