require conf/machine/am335x-evm.conf


IMAGE_FSTYPES = "wic wic.xz"

# Deactivate an extlinux.conf file
UBOOT_EXTLINUX = "0"
UBOOT_EXTLINUX_ROOT = ""
UBOOT_EXTLINUX_KERNEL_ARGS = ""
UBOOT_EXTLINUX_BOOT_FILES = ""

#UBOOT_MACHINE = "am335x_evm_config"

#KERNEL_DEVICETREE:forcevariable = " ti/omap/am335x-boneblack.dtb ti/omap/am335x-boneblack-revd.dtb ti/omap/am335x-boneblack-uboot.dtb ti/omap/am335x-boneblack-uboot-univ.dtb ti/omap/am335x-boneblack-wireless.dtb "

#ENABLE_I2C = "1"
#ENABLE_UART = "1"


#PREFERRED_PROVIDER_virtual/bootloader = "u-boot"
#PREFERRED_VERSION_u-boot = "2024.%"
#RDEPENDS:${PN} += "u-boot-env"
